### PR TITLE
Translate the README.md to english

### PR DESCRIPTION
**Pull request by gmarraff**
Hello guys, new Sysdigger here :smile: 
I found this repo really useful during my onboarding and it is now being linked to the QA Onboarding page, since more non Spanish speaking people might join the company, I thought it would  be nice to have it translated in English :smile:

### CODE REVIEW

**Comment by daviddetorres** [comment]
This is a breaking change, that would also be interesting to adapt for the title and even url of the repo. 
Any thoughts on this? 

Should we change the repo's name and url to English?

**Comment by Dlorite** [comment]
We could have a equivalent to English, but never remove the Spanish

**Comment by daviddetorres** [comment]
What about having a README_EN.md and a link from the main one?

**Comment by daviddetorres** [comment]
Another idea would be to add English translated texts below the Spanish ones. That will keep 1 single file and will solve the i18n problem.

**Comment by gmarraff** [comment]
I personally like the idea of having the translated version below the Spanish one, I think that having two files could easily bring them to drift.

**Comment by daviddetorres** [comment]
Closing this PR and waiting for another one with a translated text below the Spanish one.

**Pull request closed without merging**
